INSERT INTO Products (name, description, avail_qty, price, category_ID) VALUES
('Cotton T-Shirt', 'Basic crew-neck cotton t-shirt', 100, 19.99, 1),
('Slim-Fit Jeans', 'Slim-fit denim jeans with a faded wash', 50, 39.99, 2),
('Floral Print Sundress', 'Lightweight sundress with a floral print', 30, 49.99, 3),
('Quilted Bomber Jacket', 'Quilted bomber jacket with ribbed cuffs', 20, 69.99, 4),
('Leather Ankle Boots', 'Genuine leather ankle boots with side zip', 40, 89.99, 5),
('Canvas Tote Bag', 'Durable canvas tote bag with leather handles', 80, 29.99, 6),
('V-Neck Sweater', 'Soft v-neck sweater with ribbed hem', 60, 59.99, 1),
('Khaki Chino Pants', 'Classic khaki chino pants with slim fit', 70, 49.99, 2),
('Wrap Maxi Dress', 'Elegant wrap maxi dress with tie waist', 25, 79.99, 3),
('Wool Peacoat', 'Warm wool peacoat with double-breasted closure', 15, 99.99, 4),
('Suede Loafers', 'Suede loafers with tassel detail', 35, 79.99, 5),
('Straw Fedora Hat', 'Straw fedora hat with black band', 90, 24.99, 6),
('Striped Button-Up Shirt', 'Crisp striped button-up shirt with collar', 55, 34.99, 1),
('Cargo Shorts', 'Cargo shorts with multiple pockets', 45, 29.99, 2),
('Lace Cocktail Dress', 'Fitted lace cocktail dress with scalloped edges', 20, 89.99, 3),
('Hooded Parka', 'Heavy-duty hooded parka with faux fur trim', 10, 129.99, 4),
('Leather Knee-High Boots', 'Leather knee-high boots with block heel', 30, 119.99, 5),
('Crossbody Bag', 'Stylish crossbody bag with adjustable strap', 65, 39.99, 6),
('Crewneck Sweatshirt', 'Cozy crewneck sweatshirt with fleece lining', 75, 44.99, 1);
